# These are supported funding model platforms

github: [hieupvXmasEve]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: hieupvXmasEve
custom: https://www.buymeacoffee.com/hieupvXmasEve
